name: deploy-samiksha-loopback
on:
  # release:
  #   types: [published]
  push:
    branches:
      - release/haryana-education
jobs:
  deploy-samiksha-loopback:
    environment: release-haryana-education
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_SAMIKSHA_LOOPBACK }}
          known_hosts: "placeholder-text"

      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_SAMIKSHA_LOOPBACK }} >> ~/.ssh/known_hosts

      - name: Deploy files with rsync
        run: rsync -avz --exclude '.git' --exclude '.github' . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_SAMIKSHA_LOOPBACK }}:/home/x-admin/

      - name: Rebuild containers with docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_SAMIKSHA_LOOPBACK }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_SAMIKSHA_LOOPBACK }}
          script: |
            cd /home/x-admin/
            docker-compose up -d --build
